site_name: AI Agent Workshop
site_description: A workshop to learn about AI Agents and how to build them using Azure Foundry and GitHub Models.
site_author: Rakesh Lakshminarayanana
site_url: https://binarytrails-ai.github.io/aiagent-workshop

nav:
  # - Introduction: index.md
  - Getting Started: 00-getting_started.md
  - "LAB 1: Explore Semantic Kernel using GitHub Models":
      - Introduction: 01-lab-1-using_github_models.md
      - 1.1 Interacting with Large Language Models: 01-lab-1.1-interacting_with_llm.md
      - 1.2 Function Calling: 01-lab-1.2-function_calling.md
      - 1.3 Multi-Agent Orchestration: 01-lab-1.3-agents.md
  - "LAB 2: Azure AI Foundry Agents":
      - Introduction: 02-lab-2-using_azure_foundry.md
      - 2.1 Create an Agent from AI Studio Portal: 02-lab-2.1-create_agent_from_portal.md
      - 2.2 Working with Tools in Azure AI Foundry Agents: 02-lab-2.2-using_tools.md
      - 2.3 Multi-Agent Orchestration: 02-lab-2.3-multi_agent_orchestration.md
  - "LAB 3: Building an AI Application":
      - Introduction: 03-lab-3-deploying_ai_application.md
      - Architecture: 03-lab-3.1-ai_application_architecture.md

  # - Introduction: old/index.md
  # - Solution Architecture: old/architecture.md
  # - Security Considerations: old/security.md
  # - Getting Started: old/getting-started.md
  # # - Workshop Setup:
  # #   - BUILD Attendees: introduction-event.md
  # #   - Self-Guided Learners: introduction-self-guided.md
  # - Lab 1 Function Calling Power: old/lab-1-function_calling.md
  # - Lab 2 Grounding with Documents: old/lab-2-file_search.md
  # - Lab 3 Intro to the Code Interpreter: old/lab-3-code_interpreter.md
  # - Lab 4 Grounding with Bing Search: old/lab-4-bing_search.md
  # - Lab 5 Multilingual Visualizations: old/lab-5-multilingual.md
  # - Lab 6 Finishing Up: old/finishing-up.md
  # - Summary: old/summary.md
  # - Resources: old/resources.md
  # - Deployment: deployment.md
  # - Troubleshooting: troubleshooting.md

plugins:
  - glightbox
  - include-markdown

theme:
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
  # emoji_index: !!python/name:material.extensions.emoji.twemoji
  # emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css

# mkdocs.yml
extra_javascript:
  - js/custom-nav.js
